---

- name: install key (apt)
  become: yes
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64{{ visual_studio_code_gpgcheck | ternary("", " trusted=yes") }}] {{ visual_studio_code_mirror }}/repos/code stable main'
    filename: vscode
    state: present
  when: not visual_studio_code_skip_add_repo

- name: install VS Code (apt)
  become: yes
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present
